sudo: false

language: rust

os:
- linux
- osx
- windows

rust:
- stable
- beta
- 1.25.1

install:
- rustc -Vv
- cargo -V

script:
- cargo build --verbose
- RUST_BACKTRACE=full cargo test --verbose -- --nocapture

cache:
  cargo: true
